import { useRouter } from 'next/router'
import React, { MutableRefObject, useEffect, useState } from 'react'
import ImageSection from '../../components/image-section'
import Modal from '../../components/modal'
import { exampleCoverLetter } from '../../constants/index'

interface Props {
  exampleRef: MutableRefObject<HTMLDivElement | null>
}

const ImageSections = ({ exampleRef}: Props) => {
  const [showModal, setShowModal] = useState<boolean>(false)
  const router = useRouter()

  const handleExample = () => {
    setShowModal(true)

  }

  const handleCreate = () => {
    router.push('/create')
  }

    const data: ImageSection[] = [
        {title: 'AI has got you covered', text: 'GPT-3 is an artificial intelligence model that is able to generate human-like text. It is trained on a vast amount of data, including books, websites, and other texts. This makes it incredibly powerful at generating text that sounds natural.', src: '/images/abstract.svg', btnContent: 'Create your cover letter', btnStyle: 'bg-ice-cold-stare text-black-metal', onClick: handleCreate },
        {title: 'Cover Letter Example', text: 'If you’re wondering what a cover letter generated by AI would look like here is an example below generated by our cover letter generator', btnContent: 'See example', btnStyle:'bg-ice-cold-stare text-black-metal', src:"/images/tech-man.svg", reverse: true, onClick: handleExample}
    ]
  return (
    <div className="px-8 space-y-12 md:flex md:flex-col md:items-center">
    {data.map((section, i) => (
        <ImageSection key={i} {...section} exampleRef={exampleRef} />
    ))}
    <div className="relative mt-10">
      <Modal title="Example Cover Letter" showModal={showModal} setShowModal={setShowModal} text={exampleCoverLetter}/>
      </div>
    </div>
  )
}

export default ImageSections